name: Build and Publish
run-name: ${{ github.actor }} is building skopeo
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      DISABLE_DOCS: 1
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Install dependencies
        run: echo "Nothing to install"
      - name: Check out `containers/skopeo`
        run: git clone https://github.com/containers/skopeo
      - name: Build skopeo
        run: cd skopeo && make GO_DYN_FLAGS= BUILDTAGS=containers_image_openpgp
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/skopeo
          asset_name: skopeo-nightly
          tag: ${{ github.ref }}
          overwrite: true
          body: "Skopeo nightly"
